server:
    port: ${PORT:8080}
    forward-headers-strategy: framework

external:
    api:
        url: https://dummyjson.com/users

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        csrf:
            enabled: false
        enabled: true
        operations-sorter: method
        tags-sorter: alpha
        display-request-duration: true
        filter: true

logging:
    level:
        com.porto.pagination: INFO
        com.porto.pagination.services: DEBUG
        root: INFO
        org.springframework.web: DEBUG
        org.springdoc: DEBUG

app:
    pagination:
        default-page: 1
        default-size: 10
        max-size: 100
    cache:
        enabled: true
        duration-ms: 300000
